version: 2.1
jobs:
  test:
    parameters:
      stack:
        type: string
      redis_version:
        type: string
    docker:
      - image: cimg/base:stable
    environment:
      STACK: << parameters.stack >>
      REDIS_VERSION: << parameters.redis_version >>
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: "Running test"
          command: ./bin/test.sh "${STACK}"

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              stack: [heroku-18, heroku-20, heroku-22]
              redis_version: ["3", "4", "5", "6"]
      # The default version.
      - test:
          stack: heroku-18
          redis_version: ""
      # An exact point release version.
      - test:
          stack: heroku-20
          redis_version: "6.0.16"
