name: ci-redis

on: push

jobs:
  test:
    strategy:
      matrix:
        stack: [heroku-18, heroku-20, heroku-22]
        redis_version: ["", "4", "5", "6", "6.0.16"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Test
      run: ./bin/test.sh ${{ matrix.stack }}
      env:
        REDIS_VERSION: ${{ matrix.redis_version }}
